apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Déployé dans le même namespace qu'owuicore-main pour accéder au PostgreSQL partagé
# Le namespace est défini dans l'overlay (dev ou prod)

resources:
  - configmap.yaml
  - secrets.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
